
// #ifndef PROCESS_NAME
  #define PROCESS_NAME "League of Legends.exe"

  #define OBJECT_MANAGER 0x186CD20
  #define OBJECT_MAP_ROOT 0x28
  #define OBJECT_MAP_NODE_NET_ID 0x10
  #define OBJECT_MAP_NODE_OBJECT 0x14

  #define OBJECT_SIZE 0x3400
  #define OBJECT_ABILITY_POWER 0x1788
  #define OBJECT_ARMOR 0x12E4
  #define OBJECT_ATK_RANGE 0x1304
  #define OBJECT_ATK_SPEED_MULTI 0x12B8
  #define OBJECT_BASE_ATK 0x12BC
  #define OBJECT_BONUS_ATK 0x1234
  #define OBJECT_HEALTH 0x_DB4
  #define OBJECT_MAX_HEALTH OBJECT_HEALTH + 0x10
  #define OBJECT_LEVEL 0x339C
  #define OBJECT_MAGIC_RES 0x12EC
  #define OBJECT_MANA 0x2B4

  // Object Position
  #define OBJECT_POS 0x1F4
  #define OBJECT_X OBJECT_POS
  #define OBJECT_Z OBJECT_POS + 0x4
  #define OBJECT_Y OBJECT_POS + 0x8

  #define OBJECT_TEAM 0x4C
  #define OBJECT_TARGETABLE 0x_D1C
  #define OBJECT_NETWORK_ID 0x_CC
  #define OBJECT_VISIBILITY 0x28C
  #define OBJECT_NAME 0x2BE4
  #define OBJECT_SIZE_MULTIPLIER 0x12D4
  #define OBJECT_SPAWN_COUNT 0x2A0
  #define OBJECT_SPELL_BOOK 0x27e4
  #define OBJECT_SPELL_BOOK_ARRAY 0x488
  #define OBJECT_BUFF_MANAGER 0x21B8
  #define OBJECT_BUFF_MANAGER_ENTRIES_START OBJECT_BUFF_MANAGER + 0x10
  #define OBJECT_BUFF_MANAGER_ENTRIES_END OBJECT_BUFF_MANAGER + 0x14

  #define SPELL_SIZE 0x30
  #define SPELL_SLOT_LEVEL 0x20
  #define SPELL_SLOT_COOLDOWN_EXPIRE 0x28

  #define BUFF_SIZE 0x78
  #define BUFF_INFO 0x8
  #define BUFF_COUNT 0x74
  #define BUFF_END_TIME 0x10
  #define BUFF_INFO_NAME 0x8

  #define LOCAL_PLAYER 0x310990C
  #define VIEW_PROJ_MATRICES 0x31322A8
  #define RENDERER 0x310991C
  #define RENDERER_WIDTH 0x0
  #define RENDERER_HEIGHT 0x4
  #define GAME_TIME 0x3101384
// #endif